name: stock_management_app
description: "A new Flutter project."

publish_to: 'none'

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  logging: ^1.0.2  # Adiciona a biblioteca logging
  sqflite: ^2.0.0+4
  path: ^1.8.0 # Necessário para trabalhar com paths para o banco de dados

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0 # Adiciona a biblioteca de linting
  flutter_launcher_icons: ^0.12.0 # Verifique se há uma versão mais recente

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png # Certifique-se de que a imagem está aqui

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png" # Caminho para a imagem do ícone